# Generated by Django 4.2.4 on 2023-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=256)),
                ('message', models.CharField(default='Onboarding', max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Onboarding'), (1, 'OK'), (2, 'Disabled'), (3, 'Failure')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticDestinationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=256)),
                ('message', models.CharField(default='Onboarding', max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Onboarding'), (1, 'OK'), (2, 'Disabled'), (3, 'Failure')], default=0)),
            ],
        ),
    ]
